### ISSUE TITLE
Cannot build site (adding an article)

### ISSUE THREAD

**Issue by acao** [graphql/foundation.graphql.org#25]
`Error: Error building site: TOCSS: failed to transform "sass/style.sass" (text/x-sass): resource "sass/sass/style.sass_9f01a0c1d1634a317edafe1745cc4bff" not found in file cache`

possibly it's the version of Hugo I'm running?

**Comment by lucperkins** [comment]
Yes, I suspect that's a version issue. You'll need to install an "extended" version of Hugo with Sass support. https://gohugo.io/getting-started/installing/
