### ISSUE TITLE
members embed failing on https://foundation.graphql.org/members/

### ISSUE THREAD

**Issue by caniszczyk** [graphql/foundation.graphql.org#32]
for some reason the recent website changes killed our members embed

Ideally it should look something like this: https://graphql.org/users/

**Comment by lucperkins** [comment]
@caniszczyk @brianwarner For future reference, Hugo now forbids raw HTML in Markdown by default. That was the issue here.

**Comment by brianwarner** [comment]
Thanks @lucperkins, it looks like the solution was to put it in a shortcode, is that now the general way to approach raw html?

**Comment by lucperkins** [comment]
@brianwarner Yep! You can also allow raw HTML via configuration but I'm personally a fan of separating concerns.
